### ISSUE TITLE
listing geospatial layers + metadata

### ISSUE THREAD

**Issue by psolymos** [borealbirds/tutorials#2]
listing geospatial layers + metadata seems to be another candidate to include here, @MelinaHoule already started pulling those together.

**Comment by NKSBarker** [comment]
Good thinking, but I think we've got this covered. 

You're correct that @MelinaHoule started documenting [BAM's spatial data in a Wiki format](https://sites.google.com/site/bambiophysical/). 

She is currently exploring and testing out GeoNetwork for not just cataloging the environmental data we use, but also serving up BAM's data products. She showed me a demo on Tuesday and it's pretty exciting.  

Therefore, not sure it also needs to be cataloged here. But we [could certainly point people to the Wiki and GeoNetwork from this tutorials page](https://github.com/borealbirds/tutorials/tree/master/biophysical-data/README.md).
