### ISSUE TITLE
changing names of a, b, c, d, e, f in overall workflow

### ISSUE THREAD

**Issue by NKSBarker** [borealbirds/tutorials#4]
@psolymos  how attached are you to the  [onomatopoetic words](https://github.com/borealbirds/tutorials/blob/master/overall-bam-modelling-workflow/README.md)? Would you consider alternatives? 

Francisco suggested birds: 
- Auklet / Avocet / Albatross
- Blackbird
- Chickadee / Crow
- Dove / Duck
- Eagle
- Flycatcher / Finch / Falcon
- Grebe / Grosbeak

If we stick with the existing schema, can we at least change the F one? We need to be able to pronounce the word in conversation. I suggest
- Fudge
- Frack
- Foosh

**Comment by psolymos** [comment]
I am in favour of bird names. I can't memorize the folder names I created...

**Comment by NKSBarker** [comment]
We could just keep it simple and go with A, B, C, D, E, and F...

**Comment by NKSBarker** [comment]
[Done](https://github.com/borealbirds/tutorials/tree/master/overall-bam-modelling-workflow)
