### ISSUE TITLE
Add LICENSE to repo

### ISSUE THREAD

**Issue by psolymos** [borealbirds/tutorials#5]
Add license (eg BAM + MIT, or GPL for code etc) to rep, add CC-BY to gh pages footer.

**Comment by NKSBarker** [comment]
@psolymos are you planning to do this?

**Comment by psolymos** [comment]
yep, in the `gh-pages` branch.

**Comment by psolymos** [comment]
It is added [here](https://github.com/borealbirds/tutorials/blob/gh-pages/LICENSE), and the web pages link to [CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/).
