### ISSUE TITLE
Serve tutorials from gh-pages

### ISSUE THREAD

**Issue by psolymos** [borealbirds/tutorials#6]
@psolymos to transfer stuff to the pages and explain how to maintain.

Really, you are just editing md or Rmd files as before, but in a different branch/folder.

**Comment by NKSBarker** [comment]
In progress. 
Except I'm running into a glitch with this one. 
https://github.com/borealbirds/tutorials/tree/gh-pages/biophysical-data
https://borealbirds.github.io/tutorials/biophysical-data
@psolymos  help?

**Comment by psolymos** [comment]
The `README.md` in the `gh-pages` branch explains how to add tutorials ([here](https://github.com/borealbirds/tutorials/blob/gh-pages/README.md)).
