### ISSUE TITLE
Using QPAD's offsets

### ISSUE THREAD

**Issue by tati-micheletti** [borealbirds/tutorials#9]
Hey guys!

I managed to download QPAD (god bless drat! hehehe) and upload the offsets, but I am not sure how to use them in the model... I imagine they should work with the lme4 "offsets"  argument, but how do I separate it per specie? I tried to find documentation for it both in the package help file and in the shared drive, and couldn't really find it.

Any help deeply appreciated! :) 
Tati

**Comment by NKSBarker** [comment]
Offsets: Yes they are included in models as offsets (glm(y ~ x, family=poisson, offset=x)

If you load the data pack from 2016-12-01, data.frame OFF has the offsets. Rows are PKEYs. Columns are SPECIES by 4-letter code. 

I don't know about other people's workflows... And I haven't built multiple models for individual species yet... but here's what I think I would do. 

subset the point count dataset for the species I want. 
Then split by species code 
Then Merge the individual species datasets with the appropriate column from the offset data.frame. by PKEY. Your offset column becomes 'x' in the glm code I wrote above. 

@dstralberg  and @psolymos  -- other suggestions? 

I created two related tutorial placeholders. As you figure things out, please feel free to add content to these readmes. 

https://github.com/borealbirds/tutorials/tree/master/glm-with-offsets

https://github.com/borealbirds/tutorials/tree/master/looping-over-species

**Comment by psolymos** [comment]
You might want to use the pre-calculated `OFF` object part of the processed data package.

This gives you a GLMM example: https://github.com/psolymos/QPAD/tree/master/inst/doc/v2

**Comment by tati-micheletti** [comment]
Thanks a lot, guys!
I still have a question about it, though: 
Can I get a table just as Nicole mentioned (data pack from 2016-12-01) coming from the QPAD package? I wanted to avoid as much as I can to have data coming from "private" folders.
Nicole, once I decide how I will do it, I will describe it in the readmes. :)

**Comment by NKSBarker** [comment]
Peter will need to confirm, but from what I understand: 

QPAD produces parameter estimates from models suggesting how offsets should be generated given a set of data. (survey method, date, time, location, landcover, and tree cover). 

You can extract those previously calculated estimates and apply them to a new dataset to calculate offsets for your new dataset. 

For reproducibility, it makes sense to write your code so that it calculates offsets for whatever dataset you give it, based on the latest parameters estimates saved in the QPAD package.

If you just want to reproduce Alberto's models, it makes sense to use the previously-calculated offsets from the RData package.

**Comment by tati-micheletti** [comment]
Hi Nicole!
Ok, I understand. So if anybody else would like to reproduce Alberto's work they would either have to have access to the original BAM dataset, or to the data pack from 2016-12-01 .RData file, right? Is this .RData file ok to be public? It has been published already, right? In this case, could you please upload it to the BAM Website? This way I can redirect the download from there and people don't need to bother in asking for files. Thanks a lot! :)

**Comment by psolymos** [comment]
I think we are getting off topic from the issue. Let's move this conversation offline.

We are talking about package as 'data package' (a pre-processed chunk of data objects in a saved R workspace), and package as R package. 

* The QPAD package can be used to access available **model estimates** of singing rates and EDR. You need to have your own set of predictors if interested in predicting the correction factors or offsets (log or correction factor for a survey).
* The pre-processed offsets (`OFF` matrix, PKEY x species) has these calculated for PKEYs and species (where it makes sense) based on the BAM avian and geospatial db. These offsets used v3 of the QPAD estimates from the QPAD package.

Re Alberto's work (this is off topic!): need to check with him about what he has used. None of the RData files are OK to be public. Being published does not mean we can share. Please check data sharing policy.

**Comment by tati-micheletti** [comment]
Ok. Now I understand. I didn't know this offsets were not/could not be public.
Thanks a lot, Peter. I will add some info about the data in my module's metadata saying that if anyone wants it, they need to talk to BAM to get it. Thanks a lot!
